apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: travel-platform
data:
  NODE_ENV: "production"
  PORT: "3001"
  # MongoDB Atlas connection
  MONGODB_URI: "mongodb+srv://sarveshwaghmare101_db_user:Z3WNwIKBCUVw390a@airbnb-main.d4apnix.mongodb.net/airbnb?retryWrites=true&w=majority&appName=airbnb-main"
  # CORS frontend origins (adjust as needed)
  FRONTEND_URL: "http://localhost:3000"
  # Kafka configuration
  KAFKA_BROKERS: "kafka:9092"
